### ISSUE TITLE
Cross product

### ISSUE THREAD

**Issue by matthewpeterbailey** [matthewpeterbailey/mathemagic#11]
**Is your feature request related to a problem? Please describe.**
The cross product of 2 vectors should be calculated using mathemagic.cross()

**Describe the solution you'd like**
I'd like the function mathemagic.cross() to take in 2 vectors as arrays and return the cross product of those vectors

**Additional context**
https://mathworld.wolfram.com/CrossProduct.html

**Comment by morganPigeron** [comment]
Hello, PR #19 proposed for that

**Comment by matthewpeterbailey** [comment]
Released as v1.0.17
